// SPDX-License-Identifier: BSD-2-Clause
//
// Copyright (c) 2026 Le Sun
// Author: Le Sun
//
// Part of the FPGA AES-GCM / MACsec research prototype.
//
module hls_aes128gcm_dec (
    input  wire         ap_clk,
    input  wire         ap_rst,
    input  wire         ap_start,
    output wire         ap_done,
    output wire         ap_idle,
    output wire         ap_ready,
    input  wire [127:0] ciphertext_dout,
    input  wire         ciphertext_empty_n,
    output wire         ciphertext_read,
    input  wire [127:0] cipherkey_dout,
    input  wire         cipherkey_empty_n,
    output wire         cipherkey_read,
    input  wire [95:0]  IV_dout,
    input  wire         IV_empty_n,
    output wire         IV_read,
    input  wire [127:0] AAD_dout,
    input  wire         AAD_empty_n,
    output wire         AAD_read,
    input  wire [63:0]  AAD_length_dout,
    input  wire         AAD_length_empty_n,
    output wire         AAD_length_read,
    input  wire [63:0]  ciphertext_length_dout,
    input  wire         ciphertext_length_empty_n,
    output wire         ciphertext_length_read,
    input  wire [0:0]   end_length_dout,
    input  wire         end_length_empty_n,
    output wire         end_length_read,
    output wire [127:0] plaintext_din,
    input  wire         plaintext_full_n,
    output wire         plaintext_write,
    output wire [63:0]  plaintext_length_din,
    input  wire         plaintext_length_full_n,
    output wire         plaintext_length_write,
    output wire [127:0] tag_din,
    input  wire         tag_full_n,
    output wire         tag_write,
    output wire [0:0]   end_tag_din,
    input  wire         end_tag_full_n,
    output wire         end_tag_write
);

    test_dec inst (
        .ap_clk(ap_clk),
        .ap_rst(ap_rst),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        .ciphertext_dout(ciphertext_dout),
        .ciphertext_empty_n(ciphertext_empty_n),
        .ciphertext_read(ciphertext_read),
        .cipherkey_dout(cipherkey_dout),
        .cipherkey_empty_n(cipherkey_empty_n),
        .cipherkey_read(cipherkey_read),
        .IV_dout(IV_dout),
        .IV_empty_n(IV_empty_n),
        .IV_read(IV_read),
        .AAD_dout(AAD_dout),
        .AAD_empty_n(AAD_empty_n),
        .AAD_read(AAD_read),
        .AAD_length_dout(AAD_length_dout),
        .AAD_length_empty_n(AAD_length_empty_n),
        .AAD_length_read(AAD_length_read),
        .ciphertext_length_dout(ciphertext_length_dout),
        .ciphertext_length_empty_n(ciphertext_length_empty_n),
        .ciphertext_length_read(ciphertext_length_read),
        .end_length_dout(end_length_dout),
        .end_length_empty_n(end_length_empty_n),
        .end_length_read(end_length_read),
        .plaintext_din(plaintext_din),
        .plaintext_full_n(plaintext_full_n),
        .plaintext_write(plaintext_write),
        .plaintext_length_din(plaintext_length_din),
        .plaintext_length_full_n(plaintext_length_full_n),
        .plaintext_length_write(plaintext_length_write),
        .tag_din(tag_din),
        .tag_full_n(tag_full_n),
        .tag_write(tag_write),
        .end_tag_din(end_tag_din),
        .end_tag_full_n(end_tag_full_n),
        .end_tag_write(end_tag_write)
    );

endmodule
